spring:
  application:
    name: spring-mongo-demo
  data:
    mongodb:
      url: mongodb://localhost:27017/springdatamongo
      database: springdatamongo
server:
  port: 8181

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

springdoc:
  api-docs:
    path: /swagger-ui-custom.html
